name:<...>

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
Logger.cpp:297 file is already open
Logger.cpp:297 file is already open
interrupt_op_jni.cpp:21 Interruption Native function "initInterruptFlags" is called.
interrupt_op_jni.cpp:30 InterruptionNative function "obtainEffectInstanceIdentifier" is called.
effect_soften.cpp:43 soften4buf - enter
interrupt_op_jni.cpp:63 InterruptionNative function "interruptEffectInstance" is called.
interrupt_op_jni.cpp:66 Interruptiontask id = 0
interrupt_op_jni.cpp:45 InterruptionNative function "releaseEffectInstanceIdentifier" is called.
